### ISSUE TITLE
ESP forecast: Not enough years available to resample 

### ISSUE THREAD

**Issue by akssinghe** [nasa/RHEAS#114]
Even though db has enough data availability, ESP forecast run gives below error. 
Attached herewith are .conf file and bbox for reproducing the issue. 

Traceback (most recent call last):
  File "../.././bin/rheas", line 16, in <module>
    sys.exit(rheas.run())
  File "/home/ubuntu/RHEAS/src/rheas.py", line 99, in run
    forecast.execute(dbname, options)
  File "/home/ubuntu/RHEAS/src/forecast.py", line 130, in execute
    runVIC(dbname, options)
  File "/home/ubuntu/RHEAS/src/forecast.py", line 55, in runVIC
    models.writeForcings(method, options)
  File "/home/ubuntu/RHEAS/src/ensemble.py", line 82, in writeForcings
    self._ESP(options)
  File "/home/ubuntu/RHEAS/src/ensemble.py", line 106, in _ESP
    years.remove(self.endyear)  # remove forecast end year to ensure adequate record length in resampled dataset
ValueError: list.remove(x): x not in list

[BBox_New_LR.zip](https://github.com/nasa/RHEAS/files/2844150/BBox_New_LR.zip)
[junk_fct_esp.conf.txt](https://github.com/nasa/RHEAS/files/2844155/junk_fct_esp.conf.txt)

**Comment by nndas** [comment]
Resolved.
