### ISSUE TITLE
GPM: Input array issue when write to db

### ISSUE THREAD

**Issue by akssinghe** [nasa/RHEAS#118]
The below issue happened for the period Apr 01, 2018 - Feb 05, 2019 when gpm use for nowcast run. 
Since Mar 31, 2018 gpm data file is missing, model can not start before this date.

INFO: Running VIC...
Traceback (most recent call last):
  File "../.././bin/rheas", line 16, in <module>
    sys.exit(rheas.run())
  File "/home/ubuntu/RHEAS/src/rheas.py", line 97, in run
    nowcast.execute(dbname, options)
  File "/home/ubuntu/RHEAS/src/nowcast.py", line 200, in execute
    runVIC(dbname, options)
  File "/home/ubuntu/RHEAS/src/nowcast.py", line 29, in runVIC
    runDeterministicVIC(dbname, options)
  File "/home/ubuntu/RHEAS/src/nowcast.py", line 78, in runDeterministicVIC
    model.save(saveto, savevars)
  File "/home/ubuntu/RHEAS/src/vic/vic.py", line 609, in save
    self.saveToDB(args, initialize=initialize, skipsave=skipsave, ensemble=ensemble)
  File "/home/ubuntu/RHEAS/src/vic/vic.py", line 504, in saveToDB
    outdata[v][:, 0, i, j] = pdata[outvars[v][0]][:, outvars[v][1]]
ValueError: could not broadcast input array from shape (309) into shape (310)

**Comment by nndas** [comment]
Resolved.
