### ISSUE TITLE
Mac OSX  buildout issue w

### ISSUE THREAD

**Issue by giaMSU** [nasa/RHEAS#129]
I got errors while buildout the RHEAS. As issue #45, I installed GEOS. But it is not working. 
Could you please help me! Thanks

> __lwin_geojson.c:22:10:

 fatal error: 'json-c/json_object_private.h' file not found
#include 
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [lwin_geojson.lo] Error 1
make: *** [all] Error 1
postgis: cmmi failed: /var/folders/pz/_6_9bggs6bl4dwjl3fz2fl0h0000gn/T/tmpjTpjcmbuildout-postgis
While:
  Installing postgis.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/GIANGUYEN/RHEAS/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/Users/GIANGUYEN/RHEAS/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/GIANGUYEN/RHEAS/eggs/zc.buildout-2.13.1-py2.7.egg/zc/buildout/buildout.py", line 1603, in _call
    return f()
  File "/Users/GIANGUYEN/RHEAS/eggs/zc.recipe.cmmi-2.0.0-py2.7.egg/zc/recipe/cmmi/__init__.py", line 115, in install
    self.build()
  File "/Users/GIANGUYEN/RHEAS/eggs/zc.recipe.cmmi-2.0.0-py2.7.egg/zc/recipe/cmmi/__init__.py", line 197, in build
    self.cmmi(dest)
  File "/Users/GIANGUYEN/RHEAS/eggs/zc.recipe.cmmi-2.0.0-py2.7.egg/zc/recipe/cmmi/__init__.py", line 223, in cmmi
    system("make")
  File "/Users/GIANGUYEN/RHEAS/eggs/zc.recipe.cmmi-2.0.0-py2.7.egg/zc/recipe/cmmi/__init__.py", line 32, in system
    subprocess.check_call(c, shell=True)
  File "/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'make' returned non-zero exit status 2_

>_

**Comment by giaMSU** [comment]
I think the issue coming from the error below, but I don't know how to fix it. Please help.


_Downloading https://download.qt.io/official_releases/qt/5.12/5.12.2/single/q
Already downloaded: /home/giamsu/.cache/Homebrew/downloads/e5a2d7ee7f598b577626dc985c25e12295b25bda81034b73b235541875d3bd4d--qt-everywhere-src-5.12.2.tar.xz
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
qtbase/src/gui/configure.json:
  expected replacement of "[ \"xcb/xcb.h\", \"X11/Xlib.h\", \"X11/Xlib-xcb.h\" ]," with "[ \"xcb/xcb.h\", \"X11/Xlib.h\", \"X11/Xlib-xcb.h\", \"xcb/shm.h\" ],"_

**Comment by giaMSU** [comment]
I installed RHEAS, so closed the issue
