### ISSUE TITLE
TRMM issue

### ISSUE THREAD

**Issue by AdamJDuncan** [nasa/RHEAS#16]
Hi, I've been successful with CHIRPS precip data, but not TRMM, so I haven't been able to run the program on the Mekong.

Just to ensure it's not a problem with my Phnom Penh or Mekong basin shapefiles not aligning with the constraints set out in the INI file, I've replicated the problem with the African test basin shapefile and coordinates, both with the original and freshly downloaded data (which appears to commit to precip.trmm without any errors).

Again, CHIRPS works great, but changing precip to TRMM yields: 

```
mrc@mrc-VPCZ114GX:/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/bin$ ./rheas forecasttest.conf
Traceback (most recent call last):
  File "./rheas", line 17, in <module>
    sys.exit(rheas.run())
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/rheas.py", line 81, in run
    nowcast.execute(dbname, options)
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/nowcast.py", line 187, in execute
    runVIC(dbname, options)
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/nowcast.py", line 29, in runVIC
    runDeterministicVIC(dbname, options)
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/nowcast.py", line 75, in runDeterministicVIC
    prec, tmax, tmin, wind = model.getForcings(options['vic'])
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/vic/vic.py", line 355, in getForcings
    for v in ['precip', 'tmax', 'tmin', 'wind']}
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/vic/vic.py", line 355, in <dictcomp>
    for v in ['precip', 'tmax', 'tmin', 'wind']}
  File "/media/mrc/91413921-20fa-49f6-a9f3-5cef68ef67b8/RHEAS/src/vic/vic.py", line 314, in _getTiles
    tiles = [int(r[0]) for r in cur.fetchall()]
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by kandread** [comment]
Can you post your config file?

**Comment by AdamJDuncan** [comment]
Sorry I think the database was corrupt... we blew everything up and cloned the updated repository, got the tiffs in QGIS today, thank you!
