### ISSUE TITLE
bootstrap.py script errors (setuptools issue)

### ISSUE THREAD

**Issue by kashingtonDC** [nasa/RHEAS#42]
Hi, I'm trying to install RHEAS and I'm getting an error with the buildout script. I've tried using python 2 on MacOSX as well as Ubuntu. I'm greeted with the same error: 

`Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip
Extracting in /tmp/tmpbavxw72p
Traceback (most recent call last):
  File "bootstrap.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 124, in _do_download
  File "<string>", line 64, in _build_egg
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "<string>", line 103, in archive_context
  File "<string>", line 87, in **new**
  File "/usr/lib/python3.4/zipfile.py", line 937, in **init**
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ImportError: No module named 'apport'

Original exception was:
Traceback (most recent call last):
  File "bootstrap.py", line 98, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 173, in use_setuptools
  File "<string>", line 124, in _do_download
  File "<string>", line 64, in _build_egg
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "<string>", line 103, in archive_context
  File "<string>", line 87, in **new**
  File "/usr/lib/python3.4/zipfile.py", line 937, in **init**
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`

It looks like there is no file located at https://pypi.python.org/packages/source/s/setuptools/setuptools-20.10.1.zip

I'm not sure how to jump around this issue. Advice on bootstrapping and building is most appreciated!

**Comment by AdamJDuncan** [comment]
When you type "python -V" (note the uppercase V) what does it return?

**Comment by kashingtonDC** [comment]
Mac OSX: Python 2.7.10
Ubuntu 14.04: Python 2.7.6

**Comment by ascii766164696D** [comment]
It's related to https://github.com/pypa/setuptools/issues/557

**Comment by kashingtonDC** [comment]
Solved! Many thanks
