### ISSUE TITLE
DSSAT nowcast fails after running a forecast

### ISSUE THREAD

**Issue by vks01** [nasa/RHEAS#50]
I ran into a few DSSAT related issues - I will open separate tickets for each one, to make it easier to track - I dont think the issues are related. This installation is on an Ubuntu machine.

I was running nowcasts for the sample basin file for different years (the outcome of each of those runs is one of the issues that I will open a different ticket for). I then went back to 2001 and tried to run a forecast. The VIC forecast seemed to run through, but I had an error with the DSSAT forecast (that was related to crop growth failure - the subject of a separate issue). So, I came back and tried to re-run a nowcast using a config file that I had used right before the forecast. I got the following error: 

-----------ERROR START-------------------
Traceback (most recent call last):
  File "./bin/rheas", line 14, in <module>
    sys.exit(rheas.run())
  File "/home/ksriniva/RHEAS/src/rheas.py", line 89, in run
    nowcast.execute(dbname, options)
  File "/home/ksriniva/RHEAS/src/nowcast.py", line 199, in execute
    runDSSAT(dbname, options)
  File "/home/ksriniva/RHEAS/src/nowcast.py", line 183, in runDSSAT
    model.run(dssatexe)
  File "/home/ksriniva/RHEAS/src/dssat.py", line 698, in run
    gid, depths)
  File "/home/ksriniva/RHEAS/src/dssat.py", line 335, in readVICOutput
    gid, depths)
  File "/home/ksriniva/RHEAS/src/dssat.py", line 243, in _readVICOutputFromDB
    [r[-1] for r in results if r[1] == ens + 1]) for ens in range(vicnens)]
TypeError: range() integer end argument expected, got NoneType.

-----------ERROR END-------------------

**Comment by nndas** [comment]
Resolved.
