### ISSUE TITLE
Fetching issues with NMME, GPM, AMSRE and MOD16

### ISSUE THREAD

**Issue by akssinghe** [nasa/RHEAS#62]
Fetching issues with NMME, GPM, AMSRE and MOD16. 
Error messages are as below.

#nmme issue: ------------------------------------------------------------------------

INFO: Updating database!
Traceback (most recent call last):
  File "./bin/rheas", line 16, in <module>
    sys.exit(rheas.run())
  File "/home/ubuntu14/RHEAS/src/rheas.py", line 84, in run
    update(dbname, config_filename)
  File "/home/ubuntu14/RHEAS/src/rheas.py", line 67, in update
    mod.download(dbname, dt, bbox)
  File "/home/ubuntu14/RHEAS/src/datasets/nmme.py", line 117, in download
    f = zipfile.ZipFile("{0}/{1}_{2}.zip".format(outpath, varname, e+1))
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/tmp/tmp914qK7/Precipitation_1.zip'

#gpm issue: ---------------------------------------------------------------------------

INFO: Updating database!
ubuntu14@RHEAS:~/RHEAS$

# amsre issue: --------------------------------------------------------------------------

INFO: Updating database!
Traceback (most recent call last):
  File "./bin/rheas", line 16, in <module>
    sys.exit(rheas.run())
  File "/home/ubuntu14/RHEAS/src/rheas.py", line 84, in run
    update(dbname, config_filename)
  File "/home/ubuntu14/RHEAS/src/rheas.py", line 67, in update
    mod.download(dbname, dt, bbox)
  File "/home/ubuntu14/RHEAS/src/datasets/amsre.py", line 35, in download
    ftp.login()
  File "/usr/lib/python2.7/ftplib.py", line 393, in login
    if resp[0] == '3': resp = self.sendcmd('PASS ' + passwd)
  File "/usr/lib/python2.7/ftplib.py", line 249, in sendcmd
    return self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 224, in getresp
    raise error_perm, resp
ftplib.error_perm: 530 Login incorrect.

#mod16 issue: ---------------------------------------------------------------------------

Traceback (most recent call last):
  File "./bin/rheas", line 16, in <module>
    sys.exit(rheas.run())
  File "/home/ubuntu14/RHEAS/src/rheas.py", line 84, in run
    update(dbname, config_filename)
  File "/home/ubuntu14/RHEAS/src/rheas.py", line 67, in update
    mod.download(dbname, dt, bbox)
  File "/home/ubuntu14/RHEAS/src/datasets/mod16.py", line 38, in download
    ftp = FTP(url)
  File "/usr/lib/python2.7/ftplib.py", line 120, in __init__
    self.connect(host)
  File "/usr/lib/python2.7/ftplib.py", line 135, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

===================================
data.conf
[domain]
minlat: 5.5
maxlat: 28.75
minlon: 92.0
maxlon: 109.75

[nmme]
startdate: 2017-7-1
enddate: 2017-10-31

**Comment by kandread** [comment]
GPM issue should be fixed with #63. 
MOD16 should be fixed with #64.
AMSR-E should be fixed with #65.
Confirming NMME issue. Need to contact ClimateSERV folks.

**Comment by kandread** [comment]
Fixed NMME issue with 2b596e0479fca5cb82cb9ec8b73dd393ace58230. Closing.
