### ISSUE TITLE
Type error in NMME forecast run 

### ISSUE THREAD

**Issue by wle0001** [nasa/RHEAS#97]
I can't seem to get past this error. I've tried several different time periods. I've tried reading from a statefile, random initialization, and no initialization. The esp method appears to be working just fine. Am I missing something simple?

`Traceback (most recent call last):
  File "./bin/rheas", line 14, in <module>
    sys.exit(rheas.run())
  File "/home/Socrates/rheas/rheas/src/rheas.py", line 96, in run
    forecast.execute(dbname, options)
  File "/home/Socrates/rheas/rheas/src/forecast.py", line 100, in execute
    runVIC(dbname, options)
  File "/home/Socrates/rheas/rheas/src/forecast.py", line 57, in runVIC
    models.writeForcings(method, options)
  File "/home/Socrates/rheas/rheas/src/ensemble.py", line 146, in writeForcings
    self.__fromDataset("nmme", options)
  File "/home/Socrates/rheas/rheas/src/ensemble.py", line 154, in __fromDataset
    dsmod.generate(options, self)
  File "/home/Socrates/rheas/rheas/src/datasets/nmme.py", line 208, in generate
    prec, tmax, tmin, wind = _getForcings(options, models, models.res)
  File "/home/Socrates/rheas/rheas/src/datasets/nmme.py", line 187, in _getForcings
    tmax[e] = [(vtmax[i][0], vtmax[i][1], temp[e][i][2] + 0.5 * (vtmax[i][2] - vtmin[i][2])) for i in range(len(vtmax))]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
`
[forecast.conf.txt](https://github.com/nasa/RHEAS/files/2178202/forecast.conf.txt)

**Comment by kandread** [comment]
Can you test with the latest `develop` branch?

**Comment by nndas** [comment]
Resolved.
